language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.1
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: true

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # for tags

after_success:
  - julia -e 'cd(Pkg.dir("Simplex")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
